# -*- coding: utf-8 -*-
"""Univariate Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFzNMIYlmfXJ59vRZWk6VBUMrcrLfa95
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import spearmanr, chi2_contingency

#  Load data
# df = pd.read_csv('/Users/faitholalere/Documents/Masters/Dissertation/Data/HR_Analytics.csv')

df = pd.read_csv("/content/HR_Analytics.csv")

# split numeric and categorical variables
numeric_columns = [
    "Age","MonthlyIncome","TotalWorkingYears","YearsAtCompany",
    "YearsInCurrentRole","YearsSinceLastPromotion","PercentSalaryHike",
    "DistanceFromHome","TrainingTimesLastYear"]
categorical_columns = [
    "Gender","JobLevel","JobRole","Department","EducationField",
    "BusinessTravel","OverTime","MaritalStatus","SalarySlab",
    "JobSatisfaction","PerformanceRating","WorkLifeBalance","Attrition"]

# Adding in Binary variables so it can be used easily in my models
df["Senior_role"] = (df["JobLevel"] >= 2).astype(int) # any thing higher than 2 is a senior role lower is mid/junior
df["Attrition_binary"] = (df["Attrition"] == "Yes").astype(int) #yes = 0 (Emoloyee has left) no = 1(employee stayed)

#  Frequencies (categoricals)
for c in categorical_columns: #loops thru each variable to count
    counts = df[c].value_counts(dropna=False) # skip missing records
    print("Table to show counts & Percentage of data for each variable")
    print(f"\n{c} counts (%):")
    print(pd.DataFrame({"count": counts, "percentage": (counts/len(df)*100).round(1)}))

# Summary Stats - Variables by Gender
for col in ["MonthlyIncome","JobLevel","YearsSinceLastPromotion",
            "YearsInCurrentRole","PercentSalaryHike","TotalWorkingYears",
            "DistanceFromHome","TrainingTimesLastYear","YearsAtCompany"]:
    print(f"\n{col} by Gender:")
    print(df.groupby("Gender")[col].describe())

# Visual - Boxplots
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(3, 3, figsize=(12, 10))
plots = [
    ("MonthlyIncome","pastel"), ("JobLevel","muted"), ("YearsSinceLastPromotion","Set2"),
    ("YearsInCurrentRole","coolwarm"), ("PercentSalaryHike","Set3"), ("DistanceFromHome","Pastel1"),
    ("TrainingTimesLastYear","Pastel2"), ("YearsAtCompany","Set1")
]

for (col,pal), ax in zip(plots, axes.flat):
    sns.boxplot(data=df, x="Gender", y=col, hue="Gender", palette=pal,
                dodge=False, legend=False, ax=ax)
    ax.set_title(f"{col} by Gender")
# fig.delaxes(axes[2,2])
plt.tight_layout()

plots2 = ["JobSatisfaction","BusinessTravel","MaritalStatus",
        "PerformanceRating","WorkLifeBalance","Attrition"]

colors = ["pink", "steelblue"]
for c in plots2:
    ct = pd.crosstab(df[c], df["Gender"], normalize="columns") * 100
    ax = ct.plot(kind="bar", stacked=True, figsize=(6, 4), color=colors)
    ax.set_title(f"{c} by Gender (%)")
    ax.set_ylabel("%")
    plt.tight_layout()
    plt.show()

# Chi-square vs Gender
chi_rows = []
for c in ["JobSatisfaction","BusinessTravel","MaritalStatus",
          "PerformanceRating","WorkLifeBalance","Attrition","OverTime","Senior_role"]:
    ct = pd.crosstab(df[c], df["Gender"])
    chi2, p, dof, exp = chi2_contingency(ct)
    chi_rows.append({"var": c, "chi2": chi2, "p": p, "sig_0.05": p < 0.05})
chi_df = pd.DataFrame(chi_rows)
print("\nChi-square vs Gender:\n", chi_df)

plots3 = ["JobSatisfaction","BusinessTravel","MaritalStatus",
        "PerformanceRating","WorkLifeBalance","Attrition","OverTime","Senior_role"]

rows = []
for c in plots3:
    chi2, p, dof, exp = chi2_contingency(pd.crosstab(df[c], df["Gender"]))
    rows.append({"var": c, "chi2": chi2, "p": p, "sig_0.05": p < 0.05})

chi_df = pd.DataFrame(rows)
print("\nChi-square vs Gender:\n", chi_df)

# Contingency table of Senior_role by Gender, OverTime
ct_hl_gender = pd.crosstab(df["Senior_role"], df["Gender"])
ct_senior_overtime = pd.crosstab(df["Senior_role"], df["OverTime"])
print("\nSenior_role by Gender\n", ct_hl_gender)
print("chi-square:", chi2_contingency(ct_hl_gender)[:2])
print("\nSenior_role by OverTime\n", ct_senior_overtime)
print("chi-square:", chi2_contingency(ct_senior_overtime)[:2])
print("\n% Senior_role within Gender:\n", ct_hl_gender.div(ct_hl_gender.sum(axis=0), axis=1)*100)
print("\n% Senior_role within OverTime:\n", ct_senior_overtime.div(ct_senior_overtime.sum(axis=0), axis=1)*100)

# Job Role and level by Gender
print("\nJobLevel by Gender (% within Gender):")
print(pd.crosstab(df["JobLevel"], df["Gender"], normalize="columns") * 100)
print("\nJobRole by Gender (% within Gender):")
print(pd.crosstab(df["JobRole"], df["Gender"], normalize="columns") * 100)

# Pay vs Job Level
print("\nMonthlyIncome by JobLevel:")
print(df.groupby("JobLevel")["MonthlyIncome"].describe())

# Correlations - Spearman
adv_vars = [
    "JobLevel","MonthlyIncome","YearsSinceLastPromotion","YearsInCurrentRole",
    "PercentSalaryHike","TotalWorkingYears","Age","DistanceFromHome",
    "TrainingTimesLastYear","YearsAtCompany"
]
corr = df[adv_vars].corr(method="spearman")
print("\nSpearman correlation matrix:\n", corr)

# Correlation tests targets vs predictors
targets = ["JobLevel","MonthlyIncome"]
predictors = ["Age","TotalWorkingYears","YearsAtCompany",
              "YearsSinceLastPromotion","YearsInCurrentRole",
              "PercentSalaryHike","DistanceFromHome","TrainingTimesLastYear"]

rows = []
for tar in targets:
    for pr in predictors:
        rho, p = spearmanr(df[tar], df[pr], nan_policy="omit")
        rows.append({"target": tar, "predictor": pr, "rho": rho, "p": p, "sig_0.05": p < 0.05})
cor_tests = pd.DataFrame(rows)
cor_tests["padj_fdr"] = np.minimum(1, cor_tests["p"].rank(method="first") / len(cor_tests) * cor_tests["p"])
print("\nCorrelation tests (Spearman):\n", cor_tests)

# Attrition correlations
plots4 = [
    "DistanceFromHome","YearsAtCompany","TrainingTimesLastYear",
    "JobSatisfaction","WorkLifeBalance","PerformanceRating",
    "YearsInCurrentRole","YearsSinceLastPromotion"
]

rows = []
for v in plots4:
    rho, p = spearmanr(df[v], df["Attrition_binary"], nan_policy="omit")
    rows.append({"var": v, "rho": rho, "p": p, "sig_0.05": p < 0.05})

attr_tests = pd.DataFrame(rows)
print("\nAttrition vs predictors (overall):\n", attr_tests)

# Attrition correlations (only women)
df_f = df[df["Gender"] == "Female"].copy()

plots5 = [
    "DistanceFromHome","YearsAtCompany","TrainingTimesLastYear",
    "JobSatisfaction","WorkLifeBalance","PerformanceRating",
    "YearsInCurrentRole","YearsSinceLastPromotion"
]
rows = []
for v in plots5:
    rho, p = spearmanr(df_f[v], df_f["Attrition_binary"], nan_policy="omit")
    rows.append({"var": v, "rho": rho, "p": p, "sig_0.05": p < 0.05})

attr_tests_f = pd.DataFrame(rows)
print("\nAttrition vs predictors (female only):\n", attr_tests_f)

#  Heatmap of correlations
plt.figure(figsize=(9,7))
sns.heatmap(corr, annot=True, cmap="magma", vmin=-1, vmax=1)
plt.title("Spearman Correlations")
plt.tight_layout()
plt.show()

try:
    import statsmodels.formula.api as smf
    # Linear model for pay
    lm_pay = smf.ols(
        "MonthlyIncome ~ C(Gender) + Age + TotalWorkingYears + Education + JobLevel + C(OverTime) + C(Department)",
        data=df
    ).fit()
    print("\nLinear model: MonthlyIncome ~ predictors")
    print(lm_pay.summary())

    # Logistic for seniority
    glm_senior = smf.logit(
        "Senior_role ~ C(Gender) + Age + TotalWorkingYears + Education + C(OverTime) + C(Department)",
        data=df
    ).fit(disp=False)
    print("\nLogistic model: Senior_role ~ predictors")
    print(glm_senior.summary())
except ImportError:
    print("\n(statsmodels not installed; skip modeling or install via pip/conda)")

# Exports so I can add to disso
# Categorical frequencies
freq_tables = {}
for c in categorical_columns:
    counts = df[c].value_counts(dropna=False)
    freq_tables[c] = pd.DataFrame({"count": counts, "percentage": (counts/len(df)*100).round(1)})
table_cat_freqs = freq_tables

# Descriptives by Gender (key numerics)
desc_rows = []
for col in ["MonthlyIncome","JobLevel","YearsSinceLastPromotion",
            "YearsInCurrentRole","PercentSalaryHike","TotalWorkingYears",
            "DistanceFromHome","TrainingTimesLastYear","YearsAtCompany"]:
    gdesc = df.groupby("Gender")[col].describe()
    tmp = gdesc.reset_index().assign(var=col)
    desc_rows.append(tmp)
table_desc_by_gender = pd.concat(desc_rows, ignore_index=True)

# Correlation tables
table_corr_matrix = corr.copy()
table_corr_tests  = cor_tests.copy()

# Attrition correlations tables
table_attrition_overall = attr_tests.copy()
table_attrition_female  = attr_tests_f.copy()

# Composition tables
table_joblevel_by_gender_percentage = pd.crosstab(df["JobLevel"], df["Gender"], normalize="columns") * 100
table_jobrole_by_gender_percentage  = pd.crosstab(df["JobRole"],  df["Gender"], normalize="columns") * 100

table_desc_by_gender.to_csv("desc_by_gender.csv", index=False)
table_cat_freqs["Gender"].to_csv("gender_counts.csv")
table_corr_matrix.to_csv("spearman_corrs.csv")
table_corr_tests.to_csv("corr_tests.csv", index=False)
table_attrition_overall.to_csv("attrition_corrs_overall.csv", index=False)
table_att srition_female.to_csv("attrition_corrs_female.csv", index=False)
table_joblevel_by_gender_percentage.to_csv("joblevel_by_gender_percentage.csv")
table_jobrole_by_gender_percentage.to_csv("jobrole_by_gender_percentage.csv")


print("Tables Saved")